apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}-polybot-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}-polybot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}-polybot
    spec:
      containers:
      
        - name: {{ .Values.releaseName }}-polybot
          image: {{ .Values.image.polyRepository }}:{{ .Values.image.polyTag }}
          resources:
            limits:
             cpu: 0.5
             memory: 512Mi
          env:
            - name: LOAD_BALANCER
              value: "https://hamad.atech-bot.click"
          volumeMounts:
            - name: hamad-aws-cred
              mountPath: /root/.aws
              readOnly: true
          ports:
            - containerPort: {{ .Values.polyPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: hamad-aws-cred
          secret:
            secretName: hamad-aws-cred
      automountServiceAccountToken: false
